# Use the official Golang image as the base image
FROM golang:1.23-alpine


# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .


WORKDIR /app/cmd

# Build the Go app
RUN go build -o main .

# Expose port 50051 to the outside world
EXPOSE 50051
EXPOSE 3001

# Command to run the executable
CMD ["./main"]
